services:
  web:
    build:
      context: .
      args:
        VITE_STRAPI_BASE_URL: ${VITE_STRAPI_BASE_URL}
        VITE_STRAPI_TOKEN: ${VITE_STRAPI_TOKEN}
    expose:
      - "4173"
    restart: unless-stopped